### ISSUE TITLE
Seems to lock up in fuzz testing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/blackbody-spectrum#1]
Indicative of an infinite loop, or but that causes no input to be processed. It's happened multiple times during fuzzing, with ?ea&fuzzMouse=100.

**Comment by jonathanolson** [comment]
This is caused because reset-all doesn't reset the horizontal zoom, and you can get it to display upwards of 100,000+ tick marks fairly quickly. Since it's a stroke, Kite tries to compute the stroked bounds, which takes a WHILE.

Also has a 20% (approximate) chance of locking up automated testing.

**Comment by veillette** [comment]
The horizontal zoom in and zoom out buttons get disabled if the client zoom in/out too many times (Only one of the zoom button gets disabled). 
The reset button is now working.  I forgot to tag the commit.

**Comment by veillette** [comment]
It does not lock up while fuzzMoussing. Closing.
