### ISSUE TITLE
range for visible spectrum?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/blackbody-spectrum#10]
GraphDrawingNode:

``` js
26  var INFRARED_WAVELENGTH = 700; // in nm, max bounds for the rainbow spectrum
27  var ULTRAVIOLET_WAVELENGTH = 380; // in nm, min bound for the rainbow spectrum
```

The range of the visible spectrum is actually defined in `scenery-phet.VisibleColor`:

``` js
26    MIN_WAVELENGTH: 380,
27    MAX_WAVELENGTH: 780,
```

So unless there's a reason for blackbody-spectrum to be truncating this range. Line 26 & 27 of GraphDrawingNode should be deleted.  And the instantiation of SpectrumNode at line 77 can be changed to this, since it defaults the visible spectrum:

``` js
var spectrum = new SpectrumNode( {
      size: new Dimension2( widthSpectrum, VERTICAL_GRAPH_LENGTH ),
      opacity: 0.9,
      left: ultravioletPosition + axesPath.left
    } );
```

**Comment by ariel-phet** [comment]
@arnabp would be good to make any appropriate changes and close out this issue.

**Comment by arnabp** [comment]
The design doc states: "Visible light  rage is 400 - 700 nm (380 to 780 nm)"

Which is a bit strange that its range is stated twice without any clear indication of which should've been used. Presumably the first range was used initially but it seems clear here that the second range is the more accurate version. I'll go ahead and change these to accurately reflect the second range that is also used in `scenery-phet.VisibleColor`
