### ISSUE TITLE
Some labels shake when the temperature changes

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/blackbody-spectrum#100]
Test device: MacBook Air

Operating System: macOS Mojave 10.14.3

Browser: Chrome Version 74.0.3729.169 (Official Build) (64-bit)

Problem description: When the temperature change to values around the temperature of the light bulb, some of the label (Wavelength, the mark in the thermometer, the BGR, the 0 and 3) shake.   

Steps to reproduce:
move the thermometer down and up in values around the light bulb mark 

Screenshots:
![blackbody2](https://user-images.githubusercontent.com/26031501/59311006-53619380-8c65-11e9-8bdd-0703ddedb381.gif)

Troubleshooting information (do not edit):
Name: ‪Blackbody Spectrum‬
URL: http://phettest.colorado.edu/blackbody-spectrum/blackbody-spectrum_en.html?ea&brand=phet
Version: 1.1.0-dev.0 (require.js)
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Language: es-419
Window: 1176x722
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by arnabp** [comment]
I'm not currently seeing this issue. I'm not sure if it's something I can't see because it's platform/machine specific, or if it's just something I inadvertently fixed seeing as this is coming from phettest. I'll leave it open for the next RC.

**Comment by etwa4650** [comment]
@arnabp I have been able to replicate this, but only on older versions of macOS (10.12 and earlier) and Firefox. Also, I could only replicate within iFrame or on very small browser windows.

**Comment by KatieWoe** [comment]
@DianaTavares up to you if you find this acceptable.

**Comment by DianaTavares** [comment]
Still happening in my computer. But it was not observe in other devices and system. @KatieWoe suggest that may be a problem with the resolution of my computer. I think that it's ok to close this if is a problem only found in my computer.

**Comment by KatieWoe** [comment]
Well keep an eye out just in case
