### ISSUE TITLE
Short strings should not be centered

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#102]
For https://github.com/phetsims/QA/issues/348
This was mentioned in Slack, but I realized there was no issue created for it.

The short strings in the tool box are meant to be towards the left, but they are towards the center.  The check boxes should not move from their position in the untranslated sim.  To see this, use stringTest=X

![shouldcenter](https://user-images.githubusercontent.com/41024075/59792384-49f1b000-9291-11e9-9fe4-d532919663ed.png)

**Comment by DianaTavares** [comment]
Yes, the check boxes shouldn't move. They should be aligned to the left . Thanks for the observation Katie

**Comment by KatieWoe** [comment]
For https://github.com/phetsims/QA/issues/350 actually

**Comment by arnabp** [comment]
Text boxes are now aligned to the left. I also had to play around with the alignment and sizes of the other elements in this control panel because of this change. Leaving open for QA, please verify that the entire control panel behaves as expected.

**Comment by KatieWoe** [comment]
Looks good

**Comment by arnabp** [comment]
Reopening for testing purposes since this is directly correlated with #106 and should be spot checked for the maintenance release.

**Comment by KatieWoe** [comment]
Looks good in 1.0.1-rc.2
