### ISSUE TITLE
Make the gray saved lines 1pt thinner 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/blackbody-spectrum#103]
Amy did interviews today with the Blackbody sim, and she noticed that it is not evident that the red curve is behind the gray curve when the "Save" button is clicked. She suggests making the gray line 1 pt thinner. 
 
I think is ok! What do you think @ariel-phet ?

**Comment by arnabp** [comment]
Here is the difference for reference:
Before
<img width="822" alt="Screen Shot 2019-06-20 at 2 48 25 PM" src="https://user-images.githubusercontent.com/8583364/59880548-880ed280-936a-11e9-9607-9c2ab4115fce.png">
After
<img width="813" alt="Screen Shot 2019-06-20 at 2 48 07 PM" src="https://user-images.githubusercontent.com/8583364/59880547-87763c00-936a-11e9-9494-534e845c496c.png">

And how the saved line looks when not overlapped:
Before
<img width="823" alt="Screen Shot 2019-06-20 at 2 50 30 PM" src="https://user-images.githubusercontent.com/8583364/59880833-403c7b00-936b-11e9-9715-d9d9f1c878a8.png">
After
<img width="817" alt="Screen Shot 2019-06-20 at 2 50 56 PM" src="https://user-images.githubusercontent.com/8583364/59880844-46caf280-936b-11e9-8680-a1e3cf49a1e3.png">

**Comment by DianaTavares** [comment]
I like how it looks when the gray graph is over the red one. But I like it more when both have the same side when they are part.

**Comment by arnabp** [comment]
Agreed. Since the red line switches being being on top of the saved lines when it's moved, what I could do is restore the size of the saved line when that change happens. That way when a saved line is created it appears smaller and therefore more visible, but once interaction begins it becomes as visible as the red line.

**Comment by DianaTavares** [comment]
I like it! If it is not a lot of work, I said do it!

**Comment by ariel-phet** [comment]
Sounds good

**Comment by arnabp** [comment]
Line widths now change when certain interactions occur to match the requested behavior. Leaving this open for QA testing to verify that these behaviors have been met and no other issues appear with the saved lines and the layout order because of this.

**Comment by KatieWoe** [comment]
Looks good to me
