### ISSUE TITLE
Sim screenshots 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/blackbody-spectrum#104]
Here are the screenshots of the sim:

Principal: 
![Screen Shot 2019-06-21 at 2 43 42 PM](https://user-images.githubusercontent.com/26031501/59950665-df2caa00-9433-11e9-90a0-9b2822b8c0c5.png)

Alternatives:
![Screen Shot 2019-06-21 at 2 59 09 PM](https://user-images.githubusercontent.com/26031501/59951126-31ba9600-9435-11e9-9fb3-b50c54d818cc.png)

![Screen Shot 2019-06-21 at 3 01 16 PM](https://user-images.githubusercontent.com/26031501/59951227-73e3d780-9435-11e9-8e43-422df615d18f.png)

**Comment by KatieWoe** [comment]
Above commits should do it.  Closing.
