### ISSUE TITLE
Camera and Erase buttons too large

### ISSUE THREAD

**Issue by arnabp** [phetsims/blackbody-spectrum#106]
Due to some layout adjustment changes in #102 the camera and erase button layouts were changed. This cause them to become too large, which doesn't fit with the general phet style. These buttons should be much smaller, as they were in [1.0.0-rc.2](https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-rc.2/phet/blackbody-spectrum_all_phet.html)

**Comment by arnabp** [comment]
Camera and Erase buttons should now be back to their original sizes (plus or minus a couple pixels). You can compare to [1.0.0-rc.2](https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-rc.2/phet/blackbody-spectrum_all_phet.html) for an idea of what size it was supposed to have been.

**Comment by ariel-phet** [comment]
@arnabp we probably also want to revise the screenshot on the sim page, this might require one or two steps with @mattpen

**Comment by arnabp** [comment]
The restored buttons can be seen in [1.0.1-rc.2](https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.1-rc.2/phet/blackbody-spectrum_all_phet.html). @arouinfar can you take a look and make sure it is now the appropriate size?

**Comment by arouinfar** [comment]
Looks much better now @arnabp, thanks!

**Comment by KatieWoe** [comment]
This looks ok on 1.0.1-rc.2
