### ISSUE TITLE
Improvements to temperature slider and tick marks

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/blackbody-spectrum#107]
@kathy-phet pointed out several improvements to make regarding the slider and layout of the tick marks. Labeling these improvements as top priority for @DianaTavares since we need to do a rerelease of this sim anyhow.

KP pointed out several issues:

1. It is difficult to get reproducible numbers on the slider, which could make it more difficult to see what happens when you double or quadruple the temperature. She recommended making the slider "snappy" with increments of 5 or 10 degrees Kelvin. I think 10 degrees would be fine and easier to use. 

2. The temperature for the various objects should be chosen to be a "round number" that matches the increment chosen in (1). For instance, now the Sun is at 5764 or so, it should probably just be 5760, so it can easily be snapped to.

2. Right now, the tick marks do not correspond to any even number. they look to my eye to be about 513 degrees apart. We should make them be meaningful, and change them to be about 500 degrees apart.

3. I suggest making the actual range of the slider be 250 to 11000, and the tick marks at 500, and adjust the Earth, Light Bulb etc, tick marks to match.

**Comment by ariel-phet** [comment]
Tagging @arouinfar to see if she has any other input

**Comment by arouinfar** [comment]
@ariel-phet that all sounds good to me, and I think 10 K would be a preferable snap level. In all honesty, it's such a small increment (~1/1000 of the range) that I doubt the slider would even feel snappy.

**Comment by kathy-phet** [comment]
It's actually important that it is snappy enough to be actually reproducible to achieve the goal, so I think 1000 points is too many as that will take pretty precise pixel control given that the slider may not even be 1000 pixels tall. Could the jumps be 50 degrees, so there are ~200 points in the slider?

**Comment by DianaTavares** [comment]
I agree. 

1.  I also think that 50 K as Kathy said is good

2. Then the round number of the objects are: 
Earth 300 K
Light bulb 3000 K 
Sun surface  6 000 K
Sirius A star surface 9 900 K

3. Agree with the marks 500 degrees apart (small, 1000 for the big mark)

4. With the round number for the objects in point 2, all of them match with a thermometer mark.

**Comment by ariel-phet** [comment]
@arnabp make it so!

**Comment by kathy-phet** [comment]
This article says the sun is actually 5800K blackbody.
https://www.acs.org/content/acs/en/climatescience/energybalance/energyfromsun.html

**Comment by DianaTavares** [comment]
Sorry, I did a big step, then the temperatures are: 
Earth 300 K
Light bulb 3000 K
Sun  5 800 K
Sirius A  9 900 K

**Comment by kathy-phet** [comment]
And the blackbody temperature of the earth is 252K. It's surface is hotter because of the greenhouse effect, but we should probably use its effective blackbody temperature (as seen from space). So 250K?

**Comment by kathy-phet** [comment]
https://en.m.wikipedia.org/wiki/Effective_temperature

**Comment by DianaTavares** [comment]
and the Sirius A is 9940, then is better to use 9950 that is closer:

Earth 250 K
Light bulb 3000 K
Sun 5 800 K
Sirius A 9 950 K

**Comment by kathy-phet** [comment]
Final suggestion - I think I would stick to going up to 11,000 with the 50 deg snapping, because some stars are hotter and labels will look nicer being away from the very top.

**Comment by arnabp** [comment]
Changes have been made and approved by Kathy. Moving forward to RC testing

**Comment by KatieWoe** [comment]
All seems to be as indicated here in 1.0.2-rc.1 except one thing: The lowest temp is 200, not 250 as stated in  https://github.com/phetsims/blackbody-spectrum/issues/107#issue-468790699.  However, I think this works better and it should stay as it is.

**Comment by ariel-phet** [comment]
This seems fine to me
