### ISSUE TITLE
User feedback: continuous spectra

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/blackbody-spectrum#108]
Like most introductory discussions of thermal radiation, this presentation over-simplifies two fundamental aspects of the subject. It simplistically refers to "the peak" of the BB spectrum, and to the "color" perceived by the human eye.

The perennial confusion comes from the inherent mathematical subtlety of continuous spectra.  For a quick overview, see:

<"Where is the 'Wien peak'?" Amer. J. Phys. 71, 1322-1323 (2003).>

If you want to pursue this quagmire further, I can supply lengthy bibliographies of both examples of misleading statements, and attempts to clarify the physics buried in the mathematical confusion...

**Comment by arouinfar** [comment]
Here's a link to the reference cited by the user:
http://atoc.colorado.edu/~pilewskp/where%20is%20the%20wien%20peak.pdf

> The intensity function for blackbody radiation can be presented in wavelength bookkeeping ‘‘intensity per unit wavelength-increment’’, or in frequency bookkeeping ‘‘intensity per unit frequency increment’’. As is well known, the maxima of these curves occur at different wavelengths or frequencies, <i>ν</i> = <i>c</i>/<i>λ</i>) even though they represent the same physical spectrum. The fact that the wavelength bookkeeping places the ‘‘peak’’ of the Sun’s spectrum at about **500 nm**, remarkably close to the maximum sensitivity of the human eye, leads to perennial speculation of a causal link in human evolution. Although this hypothesis has been well debunked,<sup>2</sup> a recent paper raises the question once again.<sup>3</sup> The Sun’s ‘‘peak’’ by the frequency bookkeeping comes at about **880 nm**.

> There is yet another way to define the ‘‘Wien peak’’— one that is independent of the artifact of the dispersion rule chosen to display the spectrum. This is to integrate the Planck function in any consistent bookkeeping to find the frequency or wavelength such that one-half of the total radiation intensity falls on either side.<sup>4</sup> This definition is arguably the most physically meaningful numerical criterion for the ‘‘Wien peak’’ of the blackbody spectrum, and should be more widely taught. It places the Sun’s peak at about <b>710 nm</b>, at the extreme red end of human vision.

Reading through the reference, it seems like the user may want us to display the value at the "peak" of this so-called "median" integral (which would require some nasty numerical integration to figure out this wavelength, according to the footnote), instead of the at the true peak. I don't think this is a request that will can (or necessarily should) accommodate. 

@ariel-phet perhaps you can respond to this user? Is there anything extra we should add to the Teacher Tips?

**Comment by ariel-phet** [comment]
@arouinfar yes, I can respond to the user. I will get contact info from @oliver-phet.

I don't think we need to change anything about the presentation, the sim, or the teacher tips.

**Comment by ariel-phet** [comment]
Responded to the user, closing.

**Comment by arouinfar** [comment]
Thanks @ariel-phet!
