### ISSUE TITLE
Improvements in the design: 4 sig figs, fade in the edge of the visible spectrum 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/blackbody-spectrum#111]
Mike D suggested the next improvements for the sim design: 

- [ ]  Reduce "Graph Values" readout to 4 sig figs on the vertical axis (horizontal is good)
- [ ]  Red and purple edge on the of the vertical spectrum should have a fade (see flash version)

![image](https://user-images.githubusercontent.com/26031501/64375509-b1471280-cfeb-11e9-9c5b-f9584830339b.png)

**Comment by ariel-phet** [comment]
@DianaTavares please make these suggestions two separate issues, close this one, and then assign me, thanks!
