### ISSUE TITLE
Blue arrow covers long text

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#112]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/422.  Occurs in published sim.  Seems quite minor.
The blue arrow that controls temperature overlaps with the text above the thermometer when strings are long and the arrow is at the top.

**Visuals**
![bluearrowcovers](https://user-images.githubusercontent.com/41024075/64376606-ed777480-cfe5-11e9-827d-71ad50a6a9eb.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.4-rc.1/phet/blackbody-spectrum_all_phet.html?stringTest=long
Version: 1.0.4-rc.1 2019-09-03 21:34:31 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by DianaTavares** [comment]
The arrow can be a couple of pixels smaller

**Comment by jbphet** [comment]
I would argue against the idea of changing the size of the temperature drag handle for this.  The normal value of the string is "K" (for degrees Kelvin), so the idea that someone would translate it with anything nearly as long as the string shown above seems tremendously unlikely, and reducing the size of the drag triangle reduces its visibility and ease of use.  Also, the problem only exists at the very top of the drag handle's range.

For an example, I tried a 10 character string for "K", and it just barely overlaps with the temperature drag handle.  Here's what it looked like on Chrome:

![image](https://user-images.githubusercontent.com/3082831/64463688-29800780-d0c2-11e9-93c0-8be20ffeea4a.png)

@arouinfar and @ariel-phet - okay with you to leave this as is?

**Comment by DianaTavares** [comment]
I agree with @jbphet I don't think that "K" is going to be translated to something very large (over 10 characters). I suggest to leave it the way it is.

**Comment by arouinfar** [comment]
@jbphet I'd also vote to leave it as-is.

**Comment by arouinfar** [comment]
Since there aren't any changes we'll need to make, I'll go ahead and close.
