### ISSUE TITLE
User suggestion: increase temperature range to 0 K up to 30 000 K

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/blackbody-spectrum#120]
> But in one respect of your app modelling the blackbody spectrum I would like to go back to the former version. Now  one can adjust the temperature in a range from only ;)  200  K up to 11000 K. Of course “for normal life” this Is quite a lot and by far enough. But recently I wanted to talk to my students about 3 K background radiation and about temperatures of stars witch  emit radiation in the  x – ray region of the em spectrum. The idea was to discuss the cobe satellite or the Chandra satellite which are both of great interest for astronomy.
> Both was possible in the former version of your  fine app when the range of temperature was from 0 K up to 30 000 K. Therefor I propose to widen the range of adjustable temperatures in your app again. 
> I would – and I can image some other teachers as well  – be very glad if you could do so.

**Comment by arouinfar** [comment]
@oliver-phet I think the user is thinking of some other interactive. The range of temperatures in the Flash version is 300 - 9255 K and has been since the 1.0 release. We expanded the range in the HTML5 version to 200 - 11000 K. From what I recall (feel free to correct me if I'm wrong @DianaTavares), there were real design challenges in accommodating such a large range, and I don't think we would ever support 0 - 30000 K.

**Comment by DianaTavares** [comment]
That is true! the HTML5 version has a bigger range of temperatures that the Flash. And the issue with increasing the temperature range is to adjust the zoom to visualize all the curves in the graph. Already the user needs several clicks to move from the bigger range to the smaller. I agree with @arouinfar

**Comment by oliver-phet** [comment]
Reply to user sent, closing!

**Comment by oliver-phet** [comment]
Reply back from user: (it seems you could actually enter a value of 40,000 in the Flash version, even though the slider only went to 9255 K). 

> One – last – attempt to make clear what I meant: (see screenshot files above) Yes it was an old flash version I used to explain my students the Planck – curve and its consequences. It is as far as I know one of most important pillars of modern cosmology that the extreme coincidences of measured data with the predictions of the Planck – curve up to even that low temperatures. And therefore I think it is worth to open that wide range of adjustable temperatures. 
> The screenshots show that  one could not adjust these extreme temperatures with a gliding ruler (which is indeed not a good solution because of lack of adjustable precision) but one could just key in these values in that text field. Even if doing so was not the intended way to enter a value (maybe even a possible bug) but it worked properly !  (As a teacher for computer-science and object oriented programming with some experience in Delphi and Java I know about the chances and difficulties of programming those features)

![Planck-curve 3 K](https://user-images.githubusercontent.com/5090275/94838139-6526f700-03d2-11eb-9be0-20e097823e43.png)
![Planck-curve 40000 K](https://user-images.githubusercontent.com/5090275/94838164-6e17c880-03d2-11eb-900f-33d40f989809.png)
![Cobe](https://user-images.githubusercontent.com/5090275/94838171-7112b900-03d2-11eb-8cd8-5dab8c4ce461.PNG)

**Comment by DianaTavares** [comment]
Oh, that is true, in the flash sim you really can put any value, even negative:
![image](https://user-images.githubusercontent.com/26031501/94853621-471cbf00-03f1-11eb-80e7-46cc76c032fc.png)

Something that doesn't have sense. But the truth is that allows us to have a bigger max temperature requires a lot of changes,  the graph, and the values. It is not easy to do task.

**Comment by oliver-phet** [comment]
@DianaTavares can this issue be closed?

**Comment by DianaTavares** [comment]
yes!
