### ISSUE TITLE
Adjust max width values to better support Arabic (and other) translations

### ISSUE THREAD

**Issue by jbphet** [phetsims/blackbody-spectrum#124]
@issamali67 has been working on translating this sim into Arabic, and ran into a few issues.  He and I just met over Zoom and tried some modifications to his strings and were able to solve some of the problems that way, but there are two more changes that would help.  They are:

1. The Arabic words for Red, Green, and Blue all start with the same letter, so a single letter can't be used for the RGB display.  When a full word is used, it ends up being quite small.  If we can increase the width of these labels, the translation will look much better.
2. The translation for the checkbox label "Graph Values" ends up being significantly longer in Arabic, so it would be helpful if the max width for this label could be increased.

**Comment by jbphet** [comment]
I've committed changes for these two things.  I believe that release branches are currently considered "locked down" based on what @jonathanolson said [in this comment]](https://github.com/phetsims/states-of-matter/issues/354#issuecomment-847194427), so I'll work with him on how to get these changes into a maintenance release.

@jonathanolson - How do I go about getting the two changes listed above into a maintenance release and when is it likely to go out?

**Comment by jonathanolson** [comment]
Is it a possibility for me to just roll those patches into the latest release branch and have them tested? I just put out RCs for maintenance (so we could also wait until that's fully handled).

**Comment by jbphet** [comment]
@jonathanolson - Yes, absolutely, you can roll these changes into the release branch and incorporate them into the next RC.  Please let me know when you do and I'll double check them, but I think they are pretty straightforward.

**Comment by jonathanolson** [comment]
Rolled into the maintenance release, cherry-picked above (needed manual changes for everything, please verify), and deployed an RC at https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.8-rc.3/phet/blackbody-spectrum_all_phet.html for testing.

**Comment by jonathanolson** [comment]
Let me know if this looks ok?

**Comment by issamali67** [comment]
Question: this is the English Blackbody sim. How would I see the effects on
the Arabic translation?

**Comment by KatieWoe** [comment]
This was checked in https://github.com/phetsims/QA/issues/656. Looks ok with both `?stringTest=rtl` and `?stringTest=long`

**Comment by jbphet** [comment]
@issamali67 - You can't see the full effect on the Arabic translation from the RC version, but you _can_ see how a single string would look in place of all strings.  You and I did this when we met over Zoom and made adjustments.  To do it, you use the query parameter `stringTest=XX` where the XX is whatever string you'd like to test.  Here is a screenshot of the sim with `stringTest=مخضر` (which Google said was Arabic for "green"):

![image](https://user-images.githubusercontent.com/3082831/121736272-92c15580-cab4-11eb-8cac-96afa87e7e17.png)

**Comment by jbphet** [comment]
@jonathanolson - Yes, version 1.0.8-rc.3 looks good with respect to this issue, please feel free to move forward with publication.

**Comment by jonathanolson** [comment]
Sounds good, I'll be tracking it and will comment here once it's pushed out!

**Comment by issamali67** [comment]
I submitted the Arabic translation for Blackbody Spectrum sim.

**Comment by jonathanolson** [comment]
Closing, handled in maintenance release deployment.
