### ISSUE TITLE
CT: required tandems must be supplied

### ISSUE THREAD

**Issue by jbphet** [phetsims/blackbody-spectrum#129]
@marlitas - It looks like there is another CT error related to the usage of `TriangleNode` in addition to #128.  It is a phet-io problem and involves required tandems.  Below is the stack trace.  Please add the needed tandem(s), feel free to contact me if you need a hand.

```
blackbody-spectrum : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658948350241/blackbody-spectrum/blackbody-spectrum_en.html?continuousTest=%7B%22test%22%3A%5B%22blackbody-spectrum%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658948350241%22%2C%22timestamp%22%3A1658954788101%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658948350241/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:205:16)
at initializePhetioObject (Node.ts:6357:10)
at initializePhetioObject (Node.ts:6347:9)
at mutate (Path.ts:94:9)
at (TriangleNode.ts:45:4)
at (TriangleSliderThumb.js:46:21)
at (BlackbodySpectrumThermometer.js:80:24)
at (BlackbodySpectrumScreenView.js:49:24)
at (BlackbodySpectrumScreen.js:22:15)
id: Bayes Puppeteer
Snapshot from 7/27/2022, 12:59:10 PM
```

**Comment by marlitas** [comment]
@jbphet Thanks for dealing with me as I add more onto my list of things to test/check for when handling common-code/ other repos. 

I did fuzz testing through PhET-iO studio, state wrapper, and unbuilt. I also hand checked things were running as expected and the tree looked appropriate in PhET-iO studio. I'm hoping this caught everything. Will keep an eye on CT the next few days to make sure it's all in the clear before closing.

**Comment by marlitas** [comment]
CT looks clear. Closing.
