### ISSUE TITLE
Reset All does not reset Zoom in/ Zoom Out buttons

### ISSUE THREAD

**Issue by veillette** [phetsims/blackbody-spectrum#13]
Noticed when changing from PropertySet to Property ( #11).

 In this sim, the approach to zoom in and zoom out uses a relative zoom (+1)/ (-1) that gets then reset to zero. As a result, there is no Property that keeps track of the absolute Zooming status, making it hard to reset the simulation.

**Comment by jbphet** [comment]
I checked the behavior on master and it is definitely resetting now, and I looked at the implementation and it looks reasonable.  Closing.
