### ISSUE TITLE
complete the credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/blackbody-spectrum#16]
... in blackbody-spectrum-main.js.

**Comment by ariel-phet** [comment]
@arnabp please double check these before publication

**Comment by pixelzoom** [comment]
Be sure to check with @KatieWoe for QA credits.

**Comment by KatieWoe** [comment]
QA credits: Liam Mulhall, Jacob Romero, Ethan Ward, and Kathryn Woessner

**Comment by KatieWoe** [comment]
Steele Dalton should be added to credits.
https://github.com/phetsims/QA/issues/357

**Comment by arnabp** [comment]
Credits were completed and sim was published, closing
