### ISSUE TITLE
anti-pattern for propagating options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/blackbody-spectrum#17]
Related to #15 code review.

This sim uses the following anti-pattern:

```js
function MyType(..., options ) {
  Supertype.call( this, options );
  ...
  this.mutate( options );
}
```

`options` should be passed via either the supertype constructor _or_ `mutate`, but not both.  Doing so can lead to problems, especially for transform-related or "cumulative" options.

I'll note these in the code by adding a `//TODO` comment that references this issue.

**Comment by arnabp** [comment]
Reviewed with @jbphet, closing.
