### ISSUE TITLE
break GraphDrawingNode into smaller building blocks

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/blackbody-spectrum#19]
Noted in #15 (code review)...

GraphDrawingNode is documented as:

`* Graph Node responsible for drawing axes, spectrum, zoom buttons, axe titles and graph`

It looks like the current implementation could definitely be broken up into smaller building blocks.  At 371 lines of code, it's a bit long.

**Comment by arnabp** [comment]
The Axes and axes labels/titles have been moved to ZoomableAxesView. Zoom buttons were cleaned up a bit. Is this what you're looking for, or should this be broken down further?

**Comment by pixelzoom** [comment]
Yep, looks good.

**Comment by pixelzoom** [comment]
Something I noticed in `ZoomableAxesView`...  You have comment blocks like this:

```js
    //
    // @private
    //

    // How each axis scales
    this.horizontalZoomScale = options.horizontalZoomFactor;
    this.verticalZoomScale = options.verticalZoomFactor;
...

    //
    // @public
    //

    // {Property.<number>} current zoom values
    this.horizontalZoomProperty = new NumberProperty( options.defaultHorizontalZoom );
    this.verticalZoomProperty = new NumberProperty( options.defaultVerticalZoom );
...
```

You need to put the `@private` and `@public` annotations on a comment line before the `this.*` declarations.   If you have a bunch to `this.*` declarations on contiguous lines, you can put one `@private` or `@public` comment before the entire group.   For more info, see the [Visibility Annotations](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md#visibility-annotations) section of the code-review checklist.

**Comment by arnabp** [comment]
GraphDrawingNode was split up into itself, ZoomableAxesView, and GraphValuesPointNode
