### ISSUE TITLE
issues with blackbody-spectrum.ThermometerNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/blackbody-spectrum#2]
First, it has this nonstandard requirejs import:

> var Thermometer = require( 'SCENERY_PHET/ThermometerNode' );

Second, it creates a specialization of ThermometerNode, but does do via composition instead of inheritance. It would be preferable in this case to use inheritance, and rename blackbody-spectrum ThermometerNode to something like BlackBodySpectrumThermometerNode or BBSThermometerNode.

Noticed while working on https://github.com/phetsims/scenery-phet/issues/71.

**Comment by bereaphysics** [comment]
The BlackbodySpectrumThermometer uses inheritance from ThermometerNode instead of Node. Assigning to @pixelzoom for review

**Comment by pixelzoom** [comment]
Looking good, closing.
