### ISSUE TITLE
Make temperature cueing arrows easier to see

### ISSUE THREAD

**Issue by andrealin** [phetsims/blackbody-spectrum#27]
Can we adjust the look of the temperature cueing arrows to make them more visible? @kathy-phet and @jbphet suggested that when we were briefly looking the sim.

**Comment by andrealin** [comment]
@SaurabhTotey I was playing around with colors and `'#64dc64'` is a nice green color that is slightly brighter than `'green'`

**Comment by SaurabhTotey** [comment]
Ok, I changed the color to the one that was recommended. Does it look good now?

**Comment by andrealin** [comment]
Looks good, closing.
