### ISSUE TITLE
Where to place temperature labels for saved graphs

### ISSUE THREAD

**Issue by SaurabhTotey** [phetsims/blackbody-spectrum#31]
According to the design document, each saved graph should have a temperature label associated with it. However, I am not quite clear on where the temperature label should go. For testing purposes, I just used the old intensity label placement to place the temperature labels. However, this approach may not be sufficient because I am noticing a few issues. For example, in the image below, when saving two curves, the temperature labels are adjacent and it is difficult to tell which label corresponds to which curve.
![first](https://user-images.githubusercontent.com/22577113/43909425-924f6472-9bb7-11e8-8556-26226d7a163c.png)
One thing I tried was to move the label text closer to the peak of the graph, but then new issues arise. After moving the label closer to the peak, the label often intersects with the graph, making it hard to read, as shown in the image below.
![second](https://user-images.githubusercontent.com/22577113/43909577-e568cd1a-9bb7-11e8-9066-1d1f489f2690.png)
The design document has markups that show the label to the right of the curve, but I wasn't able to figure out if there was a general pattern or specific way that labels should go in relation to the curve. In short, I am not quite sure where to place the saved curve temperature label in relation to the actual saved curve.

**Comment by DianaTavares** [comment]
The issues that we have had with this sim design is that is not a good idea to have information inside the graph because in can get lost with the visible spectrum or with the zooms. 
My proposal is  to move this temperature values outside the graph. 

![screen shot 2018-08-09 at 11 39 34 am](https://user-images.githubusercontent.com/26031501/43916182-176f75ae-9bca-11e8-825f-17867209b27e.png)

@arouinfar help me to think in this solution to have the last saved curve in solid line and the one before using dash lines. When the user save a new curve when it's already two in the sim, then the 9109 K curve (the one used in the picture as example) now is going to be dash, the 8592 is going to disappear and the new saved curve is going to be solid. 

waiting for @ariel-phet opinion

**Comment by ariel-phet** [comment]
@DianaTavares @arouinfar what about the following design.

One thing that has bugged me for awhile is that the temperature readout being right on the slider thumb of the thermometer leads to a very big "dead space", in addition, you are likely to cover that readout with your finger if using a touch device. Also, the controls for the graph do not really have good proximity to the graph. In this design I try to solve some of those issues, and use alignment to cleanly associate the thermometer with the graph. 

![bb](https://user-images.githubusercontent.com/4051174/43970846-243bee76-9c8c-11e8-90f1-42847e608253.png)

**Comment by ariel-phet** [comment]
@arouinfar @DianaTavares obviously the above is not polished (needs to be better aligned and such, but see if you like that general direction.

**Comment by DianaTavares** [comment]
Taking the @ariel-phet suggestion and working with @arouinfar, this is the proposal: 

![screen shot 2018-08-10 at 12 29 58 pm](https://user-images.githubusercontent.com/26031501/43974895-1f459ca2-9c99-11e8-8350-c5b3ffa64ac6.png)

If three curves are in the graph, I think that is important that all of them have the temperature value, for that reason the red curve was added.

With the word "intensity" and the value now closer, the suggestion is change the checkboxes order and add the value of the intensity close to the word. When this checkbox is not selected, the rectangle around this options is going to be smaller, but it is not going to move the curve values.
 
![screen shot 2018-08-10 at 12 48 13 pm](https://user-images.githubusercontent.com/26031501/43975687-a9da0c3e-9c9b-11e8-8932-1eb35d26f18a.png)

The values of the the temperature of the curves will appear only when at last one curve is saved, like is shown in the next mockups:

When any curve is save:
![screen shot 2018-08-10 at 12 51 41 pm](https://user-images.githubusercontent.com/26031501/43975848-3019cb0e-9c9c-11e8-8447-e55932a67ef9.png)

When at last one curve is save:

![screen shot 2018-08-10 at 12 51 55 pm](https://user-images.githubusercontent.com/26031501/43975864-3705ce22-9c9c-11e8-80bd-e00923a6bfd9.png)

**Comment by ariel-phet** [comment]
@DianaTavares I like this direction, we will probably still need to do some polishing once we play with it, but overall I think the layout is much better.

**Comment by ariel-phet** [comment]
@SaurabhTotey it looks like you have been working on this layout, I would say continue. When you have a working version, please publish a dev version for us to look at.

**Comment by SaurabhTotey** [comment]
[Here](https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-dev.8/phet/blackbody-spectrum_en_phet.html) is a link to the dev version for how this looks so far.

**Comment by DianaTavares** [comment]
I love it @SaurabhTotey excellent work, thanks!!

**Comment by arouinfar** [comment]
The new layout is looking really nice @SaurabhTotey!

**Comment by DianaTavares** [comment]
This implementation is already done an looks amazing! Nice work @SaurabhTotey! closing
