### ISSUE TITLE
Do we need support for projector mode?

### ISSUE THREAD

**Issue by arnabp** [phetsims/blackbody-spectrum#35]
This sim has a black background so it seems like a good thing to have a projector mode. Should we try to make this happen?

**Comment by DianaTavares** [comment]
I have this ideas for the design (I share it with Amy and she is agree)

All the strokes and text is black, except for the temperature readout that match with the color of the slide in the thermometer.
The saved lines has a darker gray color (to have a better contrast with the white background) the The star (close to the RGB colors) has stroke to be able to see it when the start is white. 
The rest of the colors are the same.

This are some mockups (I need to change some buttons according with last meeting, but it's the general idea):

![screen shot 2018-09-25 at 3 11 49 pm](https://user-images.githubusercontent.com/26031501/46043516-7519eb00-c0d5-11e8-9316-d2a44036ade0.png)
![screen shot 2018-09-25 at 3 11 59 pm](https://user-images.githubusercontent.com/26031501/46043519-76e3ae80-c0d5-11e8-8d31-5c35c947936d.png)
![screen shot 2018-09-25 at 3 12 15 pm](https://user-images.githubusercontent.com/26031501/46043523-78ad7200-c0d5-11e8-8685-e66b3543b730.png)

What do you think @ariel-phet

**Comment by ariel-phet** [comment]
@DianaTavares looks good to me and clear contrast. @arnabp lets go with this for the moment, we can always make a few minor tweaks if necessary once implemented.

**Comment by jbphet** [comment]
@arnabp - we can look at this together when you're ready, but if you want to start checking out an existing implementation of projector mode support, you can start looking at the file `SOMColorProfile` and usages thereof.  This is in the States of Matter simulation.

**Comment by DianaTavares** [comment]
This mode is working well, closing this issue
