### ISSUE TITLE
Mike suggestions: "AutoScale" button and minimum thermometer's value at 3 K

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/blackbody-spectrum#37]
@arouinfar  and I showed the new version of the sim to Mike Dubson and he has some suggestion to be considered for implementation: 

- Include lower temperatures, till 3 K, that is the background radiation 

- Include an “Auto Scale” button, that  it’s  useful if we add lower temperatures (because the zoom buttons will need more range) 

He share [this link](https://phet-dev.colorado.edu/blackbody-spectrum/2.02.02/blackbody-spectrum_en.html) of the sim where this features are implemented.

@ariel-phet suggest to discuss those in design meeting, but that autoscale has been very problematic in the past.

**Comment by arouinfar** [comment]
While autoscale seems handy, I don't think it would be necessary. It would likely add a lot of development time to the sim. The current implementation doesn't seem optimized, either.

For example, autoscale produces the zoom level on the left, but should have probably zoomed out an additional time on the x-axis (right).
<img src="https://user-images.githubusercontent.com/8419308/46705109-55adb280-cbeb-11e8-9aba-a8cfa17a2f0b.png" width=300> <img src="https://user-images.githubusercontent.com/8419308/46705150-7fff7000-cbeb-11e8-8228-3fd5b8b7c3b3.png" width=300>

I do like the idea of going all the way down to 3K, as it would correspond to the cosmic microwave background. One option would be to have a separate screen for cold temperatures. The range could go 3K-300K, potentially with these benchmarks:

| Benchmark | Avg T |
|---|---|
| Earth | 300 K |
| Mars | 210 K |
| Pluto | 44 K |
| CMB | 3 K |

Some features don't seem particularly useful below 300 K, including the BGR readout, rainbow in the graph, and the electromagnetic spectrum labels (it'd all be radio).

Even with a narrow range of 3-300K, the scaling of the Spectral Radiance is still somewhat tricky, as the values would range ~10^-15 (3 K) to ~10^-5 (300 K). With such a range, we would need at least 10-20 zoom steps. (One or two for every order of magnitude).

Thoughts @ariel-phet @DianaTavares? If you would like to explore a "cold" screen, @DianaTavares and I can work on a mockup.

**Comment by arouinfar** [comment]
Okay, sounds good @ariel-phet. I'll unassign myself until a decision has been made in design meeting.

**Comment by DianaTavares** [comment]
We decided not to make these changes in the October 18,2018 design meeting.
