### ISSUE TITLE
Suggestion: Snap slider in 50 or 100 K increments

### ISSUE THREAD

**Issue by arouinfar** [phetsims/blackbody-spectrum#38]
The temperature slider is completely continuous allowing for any value within the slider range. Because the range is so large, it is somewhat difficult to set a precise value. Perhaps the slider could be restricted to values divisible by 50 or 100 K?

Mike's revised version of Blackbody Spectrum snaps in 50 K increments:
https://phet-dev.colorado.edu/blackbody-spectrum/2.02.02/blackbody-spectrum_en.html

In general, we have been making our sliders snappier to allow for easily reproducible experiments, and I think Blackbody Spectrum would also benefit. 

@DianaTavares what do you think?

**Comment by DianaTavares** [comment]
I like the idea! I think that snaps in 50 K is perfect!

**Comment by DianaTavares** [comment]
This suggestion was accepted in design meeting Oct 18, 2018. It's going to be part of the list of We pixel polish round 2
