### ISSUE TITLE
changes in limits of the zoom options

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/blackbody-spectrum#39]
In the actual simulation of Blackbody we lose the curve shape of the spectral radiance for low temperatures for the allowed zoom values. For now the lowest range in y-axe si 0-10 and we lost the shape for all the temperatures below 2000K.

![screen shot 2018-10-18 at 7 04 08 pm](https://user-images.githubusercontent.com/26031501/47192153-9ce12500-d308-11e8-8565-bea7fb9ea1bd.png)

For all the temperatures in the simulation should be posible see clearly the shape and peak of the graph, and looking the original sim the smallest y-axe value it's 0.0003 and for x-axe it's 48. 

![screen shot 2018-10-18 at 7 18 29 pm](https://user-images.githubusercontent.com/26031501/47192443-9fdd1500-d30a-11e8-9de0-7b206f17b069.png)

The solution for the x-zoom is allow 2 extra clics for the (- )zoom for get to 48

For y-zoom that is a range from 0.0003 to 1000, We still thinking about the best solution, because with the X3 factor that we have now in the zoom bottoms, it's going to need 14 clicks and it's a lot. 

@ariel-phet suggest a Logarithmic zoom, but the fist clicks go from 0.0003 to 300, losing visualization of the temperatures 400 to 3500 K. 

Other ideas for go from 0.0003 to 1000 in small number of clicks (I was trying 6) and don't lose so many curves?

**Comment by DianaTavares** [comment]
with 8 clicks to change the zoom, this is the proposal for maxima values for Y-axe  in each click (in the table you can see what temperatures can be analyzed in each zoom option):

* The default value is start in Y-axe max value = 100

Temperature | Peak value | Max value in Y-axe in each clic
-- | -- | --
300 | 0.00001004408618 | 0.00005
400 | 0.00004232569651 |  
500 | 0.000129167775 | 0.0007
600 | 0.0003214107579 |  
700 | 0.0006946952942 |  
800 | 0.001354422288 | 0.007
900 | 0.002440712943 |  
1000 | 0.0041333688 |  
1100 | 0.006656831786 |  
1200 | 0.01028514425 | 0.1
1300 | 0.01534690902 |  
1400 | 0.02223024941 |  
1500 | 0.03138776933 |  
1600 | 0.04334151323 |  
1700 | 0.05868792624 |  
1800 | 0.07810281417 |  
1900 | 0.1023463035 | 1
2000 | 0.1322678016 |  
2100 | 0.1688109565 |  
2200 | 0.2130186172 |  
2300 | 0.2660377934 |  
2400 | 0.3291246161 |  
2500 | 0.4036492969 |  
2600 | 0.4911010886 |  
2700 | 0.5930932451 |  
2800 | 0.7113679813 |  
2900 | 0.8478014333 |  
3000 | 1.004408618 | 20
3100 | 1.183348395 |  
3200 | 1.386928423 |  
3300 | 1.617610124 |  
3400 | 1.87801364 |  
3500 | 2.170922794 |  
3600 | 2.499290053 |  
3700 | 2.866241483 |  
3800 | 3.275081713 |  
3900 | 3.729298892 |  
4000 | 4.232569651 |  
4100 | 4.788764065 |  
4200 | 5.401950608 |  
4300 | 6.076401116 |  
4400 | 6.816595749 |  
4500 | 7.627227946 |  
4600 | 8.51320939 |  
4700 | 9.479674964 |  
4800 | 10.53198771 |  
4900 | 11.67574381 |  
5000 | 12.9167775 |  
5100 | 14.26116608 |  
5200 | 15.71523484 |  
5300 | 17.28556203 |  
5400 | 18.97898384 |  
5500 | 20.80259933 | 100
5600 | 22.7637754 |  
5700 | 24.87015176 |  
5800 | 27.12964587 |  
5900 | 29.55045792 |  
6000 | 32.14107579 |  
6100 | 34.91027999 |  
6200 | 37.86714864 |  
6300 | 41.02106243 |  
6400 | 44.38170955 |  
6500 | 47.95909068 |  
6600 | 51.76352397 |  
6700 | 55.80564993 |  
6800 | 60.09643647 |  
6900 | 64.6471838 |  
7000 | 69.46952942 |  
7100 | 74.57545307 |  
7200 | 79.97728171 |  
7300 | 85.68769443 |  
7400 | 91.71972747 |  
7500 | 98.08677914 |  
7600 | 104.8026148 | 700
7700 | 111.8813718 |  
7800 | 119.3375645 |  
7900 | 127.1860892 |  
8000 | 135.4422288 |  
8100 | 144.1216586 |  
8200 | 153.2404501 |  
8300 | 162.815077 |  
8400 | 172.8624195 |  
8500 | 183.3997695 |  
8600 | 194.4448357 |  
8700 | 206.0157483 |  
8800 | 218.131064 |  
8900 | 230.809771 |  
9000 | 244.0712943 |  
9100 | 257.9354999 |  
9200 | 272.4227005 |  
9300 | 287.55366 |  
9400 | 303.3495988 |  
9500 | 319.8321985 |  
9600 | 337.0236069 |  
9700 | 354.9464429 |  
9800 | 373.6238019 |  
9900 | 393.0792601 |  
10000 | 413.33688 |  
10100 | 434.421215 |  
10200 | 456.3573145 |  
10300 | 479.1707289 |  
10400 | 502.8875147 |  
10500 | 527.534239 |  
10600 | 553.137985 |  
10700 | 579.7263564 |  
10800 | 607.327483 |  
10900 | 635.970025 |  
11000 | 665.6831786 |  
 
A change that I see is going to be needed in the sim is that when the Y-peak value it's below to 1, it have to show the first significant figure for each temperature (for example 0.8 for T=2900, and 0.0003 for T=600)

What do you think about this values?

**Comment by arouinfar** [comment]
@DianaTavares and I had a chat about the y-axis scaling. I think its important for the zoom buttons to have a consistent spacing (whether that is factors of 3, logarithmic, or whatever). I don't particularly have a problem with extreme temperatures taking a few extra zoom clicks, as there's some physicality to it. 

@DianaTavares mentioned that a factor of 5 scaling on the y-axis would require 10 steps of zoom. Given the large range of values, 10 steps seems reasonable to me. It's also on par with the number of steps on the x-axis, which will be 7.

I'd be in favor of trying out the factor of 5 scaling on the y-axis to see how things look.

**Comment by DianaTavares** [comment]
Perfect, then I am going to add this to the issue #40 in the list of polishing round 2. Thanks for your help!
