### ISSUE TITLE
Pixel polishing round #2

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/blackbody-spectrum#40]
In the 10/18/2018 sim design meeting, looking the actual version in PhET test for UI adjustments. Here is the TODO list that resulted:

- [x] The cues arrows for the Graph Values should be the same size that the ones in the thermometer.

- [x] Change the color of  the dot of Graph Values to white in the normal view and black in the projector mode.

- [x] Hide the coordinate of the dot (the one inside the blue circule in the picture) when the numbers are bigger that the axe value. 
![46772807-1f3d6980-ccb7-11e8-9a41-b88598560f29](https://user-images.githubusercontent.com/26031501/47191965-5939eb80-d307-11e8-8a87-7638bf881ebc.png)

- [x] increase the size of the text for the intensity value and a bigger space between the text and the red rectangle 
![screen shot 2018-10-18 at 9 05 22 pm](https://user-images.githubusercontent.com/26031501/47195530-9018fd00-d319-11e8-96b7-946e9f73595c.png)

- [x] make the line of labels thinner
![screen shot 2018-10-18 at 9 08 38 pm](https://user-images.githubusercontent.com/26031501/47195651-04ec3700-d31a-11e8-9242-d652214b2d3d.png)

**Comment by DianaTavares** [comment]
In #39  was decided to change the zoom limits to be able to see the curve for all the temperatures in the simulation.  The this is added to the polishing list:

- [ ] For the x-zoom  allow 2 extra clics for the (- )zoom for get to 48

- [ ] For the y-zoom the  factor of change in each click is going to be 5.  The max value is going to be 700 and in each click in the (+) zoom the max number is going to be divided by 5 rounded to a significant figure.  It's going to allow 11 clicks in total.  Something like this:

Max value in y-axe | click number
-- | --
0.00001 | 11
0.00007 | 10
0.0004 | 9
0.002 | 8
0.009 | 7
0.04 | 6
0.22 | 5
1.12 | 4
5.6 | 3
28 | 2
140 | 1
700 |  

 140 zoom is going to be the default

**Comment by arnabp** [comment]
All changes implemented in [1.0.0-dev.12 dev version](https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-dev.12/phet/blackbody-spectrum_en_phet.html). Label sizes and decimals have been changed to accommodate the scaling, probably something worth looking at in design.

**Comment by DianaTavares** [comment]
Nice work @arnabp! 
in the version that dev.12 the line for the labels of the electromagnetic spectrum still bold. Can you make it a little thinner? 

![screen shot 2018-11-05 at 11 18 55 am](https://user-images.githubusercontent.com/26031501/48017849-9a464400-e0ec-11e8-816c-40a7e76ca3bf.png)
thinner like this line (half of side that the line in the Y axe): 
![screen shot 2018-11-05 at 11 20 02 am](https://user-images.githubusercontent.com/26031501/48018714-ca8ee200-e0ee-11e8-9b86-82963a027691.png)

And also, the range of values for the electromagnetic spectrum is not correct. Infrared should be from 700 nm (.7 mictrom) to 10^5 nm (100 microm) 

![screen shot 2018-11-05 at 11 26 28 am](https://user-images.githubusercontent.com/26031501/48018782-fb6f1700-e0ee-11e8-81ef-170ec5bea347.png)

**Comment by arnabp** [comment]
Appropriate changes were made, see next round of pixel polishing at https://github.com/phetsims/blackbody-spectrum/issues/62
