### ISSUE TITLE
Cue arrows overlap with Y axis values

### ISSUE THREAD

**Issue by phet-steele** [phetsims/blackbody-spectrum#41]
1. Zoom all the way out an the X axis.
2. Enable "Graph Values"

The cue arrows for the point will overlap the Y value. I have no idea how to address this, or if we even should. I'm just pointing it out. 😄

![image](https://user-images.githubusercontent.com/5863899/47980330-659ea200-e084-11e8-9499-ec731e68c4ca.png)

Seen on Win 10 Chrome. For phetsims/QA/issues/215.

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-dev.12/phet/blackbody-spectrum_en_phet.html
Version: 1.0.0-dev.12 2018-11-02 23:46:56 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
Language: en-US
Window: 1920x938
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"cca8e36e","branch":"master"},"blackbody-spectrum":{"sha":"3db65ad6","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"fa2fbadf","branch":"master"},"dot":{"sha":"bbbd8526","branch":"master"},"joist":{"sha":"82521d0c","branch":"master"},"kite":{"sha":"380cef53","branch":"master"},"phet-core":{"sha":"1b90ac2f","branch":"master"},"phet-io":{"sha":"e230c094","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"246085c1","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"7479b0ec","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"c46f7839","branch":"master"},"phet-io-wrappers":{"sha":"ded21e3f","branch":"master"},"phetcommon":{"sha":"cd63d89a","branch":"master"},"query-string-machine":{"sha":"06ed6276","branch":"master"},"scenery":{"sha":"5013941c","branch":"master"},"scenery-phet":{"sha":"2286294f","branch":"master"},"sherpa":{"sha":"97e70540","branch":"master"},"sun":{"sha":"a423abfb","branch":"master"},"tambo":{"sha":"296cf3ba","branch":"master"},"tandem":{"sha":"1b93c58b","branch":"master"}}
</details>

**Comment by DianaTavares** [comment]
Thanks for pointing it out! I don't know neither how to solve this. probably the numbers over the arrow?  I am going to think in other options 
![screen shot 2018-11-05 at 11 05 02 am](https://user-images.githubusercontent.com/26031501/48017104-aaf5ba80-e0ea-11e8-9347-1a3d42fa3ac6.png)

**Comment by arnabp** [comment]
Hey @DianaTavares can you take a look at this again and think about what we wanna do with this? We're finishing up the sim soon.

**Comment by DianaTavares** [comment]
I like this Amy's suggestion, the labels are more important that the arrow, and its hard to read them when the arrow and the number are in the same place
![Screen Shot 2019-04-16 at 2 21 11 PM](https://user-images.githubusercontent.com/26031501/56241514-43597900-6053-11e9-9250-359ccf59e885.png)
Then, put a black (or white in the proyector mode) background to the numbers that cover the arrow
![Screen Shot 2019-04-16 at 2 22 32 PM](https://user-images.githubusercontent.com/26031501/56241553-5e2bed80-6053-11e9-8ddd-511ba50a5366.png)

**Comment by arnabp** [comment]
The text now has a black background which the arrows now go behind.
