### ISSUE TITLE
Dilate Reset All button touch area

### ISSUE THREAD

**Issue by phet-steele** [phetsims/blackbody-spectrum#44]
The touch area for the Reset All button should be made larger than the button itself. See phetsims/friction/issues/65 for an example.

For phetsims/QA/issues/215.

**Comment by arnabp** [comment]
Dilation added, closing

<img width="407" alt="screen shot 2018-11-05 at 4 13 57 pm" src="https://user-images.githubusercontent.com/8583364/48032688-db068300-e115-11e8-8eaf-ebce8043633b.png">
