### ISSUE TITLE
Be more transparent about the number of saved curves allowed

### ISSUE THREAD

**Issue by phet-steele** [phetsims/blackbody-spectrum#49]
It is not super clear that you can only save two curves. This isn't too harmful, but it also seems like unnecessarily hidden information that you can only learn "the hard way" (your earliest curve is lost when attempting to save a third 😢).

Please ignore the crappy dashes! This is the first idea I had to make it clear that two curves can be saved:

![image](https://user-images.githubusercontent.com/5863899/47981860-b9ac8500-e08a-11e8-8b9a-78a96cffb767.png)

This legend would ALWAYS show instead of just appearing when a curve is saved. When a curve is saved, the user can see values populate the legend each time, maybe making it more clear that it can only store two curves. This idea might not achieve perfect transparency on this "mechanic", but I think it's a step in the right direction. I invite other ideas from @ariel-phet and @DianaTavares.....and everyone else!

For phetsims/QA/issues/215.

**Comment by DianaTavares** [comment]
I like the idea of show always the legend with the dash lines when it's not a saved curve

**Comment by ariel-phet** [comment]
@DianaTavares @phet-steele I don't really like the idea of always showing the legend. I think it helps cue the user what has happened that the legend appears when they click save. To address @phet-steele concern, I suggest that the first time you press save the legend appears but with one blank space, as shown below. If that works for you @DianaTavares please assign to Arnab

![bb](https://user-images.githubusercontent.com/4051174/48040441-30528c80-e136-11e8-8293-24fde0702b39.PNG)

**Comment by DianaTavares** [comment]
Yes, I like that idea!

**Comment by arnabp** [comment]
Implemented the blank third saved graph slot. Not seeing any unexpected issues with it, looks good 👍

**Comment by DianaTavares** [comment]
Good job @arnabp, works very well. Closing!!
