### ISSUE TITLE
Why does the graph value point "reset" when temperature is changed?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/blackbody-spectrum#51]
Why does the graph value point jump to the peak of the curve whenever I change temperature? I don't have a case for why it should, but I do know it is somewhat annoying that it does. This prevents me from ever watching the values change with temperature at a location on the curve that I want.

For phetsims/QA/issues/215.

**Comment by DianaTavares** [comment]
I see your point. I think that both visualizations are important. In one side, to see how the pack values change when the temperature change, and in the other side, set a wavelength and see how the spectral radiance change with the temperature. 

I don't know if is posible do both. I think that si better to ask this in a design meeting.

**Comment by DianaTavares** [comment]
In the design meeting was decide that the actual behavior, where the dot moving with the peck is the the better for this simulation. Closing !
