### ISSUE TITLE
Graph value point is lost behind star

### ISSUE THREAD

**Issue by phet-steele** [phetsims/blackbody-spectrum#56]
I feel like the graph value point getting lost behind the star is unbecoming:

![image](https://user-images.githubusercontent.com/5863899/47983460-9dabe200-e090-11e8-9caa-76405cb87a0f.png)

This could be fixed by:
1. Layering the point in front of everything and...
2. ...adding a stroke around the point to help with contrast over the star (and other areas)

@DianaTavares what do you think?

Seen on Win 10 Chrome. For phetsims/QA/issues/215.

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-dev.12/phet/blackbody-spectrum_en_phet.html
Version: 1.0.0-dev.12 2018-11-02 23:46:56 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
Language: en-US
Window: 1920x938
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"cca8e36e","branch":"master"},"blackbody-spectrum":{"sha":"3db65ad6","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"fa2fbadf","branch":"master"},"dot":{"sha":"bbbd8526","branch":"master"},"joist":{"sha":"82521d0c","branch":"master"},"kite":{"sha":"380cef53","branch":"master"},"phet-core":{"sha":"1b90ac2f","branch":"master"},"phet-io":{"sha":"e230c094","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"246085c1","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"7479b0ec","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"c46f7839","branch":"master"},"phet-io-wrappers":{"sha":"ded21e3f","branch":"master"},"phetcommon":{"sha":"cd63d89a","branch":"master"},"query-string-machine":{"sha":"06ed6276","branch":"master"},"scenery":{"sha":"5013941c","branch":"master"},"scenery-phet":{"sha":"2286294f","branch":"master"},"sherpa":{"sha":"97e70540","branch":"master"},"sun":{"sha":"a423abfb","branch":"master"},"tambo":{"sha":"296cf3ba","branch":"master"},"tandem":{"sha":"1b93c58b","branch":"master"}}
</details>

**Comment by ariel-phet** [comment]
Seems like it should be layered in front....since it is the interactive element

**Comment by DianaTavares** [comment]
I like the idea of put the pint in from of everything. But I don't think that need a stroke because the color of the dot be itself is contrast from the star and other areas

**Comment by DianaTavares** [comment]
@arnabp, please layering the point in front of everything

**Comment by KatieWoe** [comment]
There can be some odd cases with lines behind the star as seen here, but they may be acceptable edge cases.
![odd](https://user-images.githubusercontent.com/41024075/48168173-86950c00-e2ab-11e8-8e4f-76d27a9350b1.PNG)

**Comment by DianaTavares** [comment]
In 11/8 design meeting was discussed that the graph will stay only inside the graph space (its not going to go to over the star. Mentioned in issue #62. Closing this issue.
