### ISSUE TITLE
Graph value point can be lost off screen

### ISSUE THREAD

**Issue by phet-steele** [phetsims/blackbody-spectrum#57]
The graph value point can be lost by:

1. Enable Graph Values
2. Zoom in the Y axis until the point goes off the top of your screen.

From here, the point cannot be retrieved without zooming the graph back out or lowering temperature. This is not a big deal, but it does seem easily avoidable. @DianaTavares @ariel-phet I would suggest allowing the point to also be draggable by either the value labels (so clicking on the numbers by the X and Y axis) or by the dashed guide lines, or both!

I'm thinking something similar to the partition lines in area model and how they can be moved by clicking directly on them instead of just the handle.

Seen on Win 10 Chrome. For phetsims/QA/issues/215.

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-dev.12/phet/blackbody-spectrum_en_phet.html
Version: 1.0.0-dev.12 2018-11-02 23:46:56 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
Language: en-US
Window: 1920x938
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"cca8e36e","branch":"master"},"blackbody-spectrum":{"sha":"3db65ad6","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"fa2fbadf","branch":"master"},"dot":{"sha":"bbbd8526","branch":"master"},"joist":{"sha":"82521d0c","branch":"master"},"kite":{"sha":"380cef53","branch":"master"},"phet-core":{"sha":"1b90ac2f","branch":"master"},"phet-io":{"sha":"e230c094","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"246085c1","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"7479b0ec","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"c46f7839","branch":"master"},"phet-io-wrappers":{"sha":"ded21e3f","branch":"master"},"phetcommon":{"sha":"cd63d89a","branch":"master"},"query-string-machine":{"sha":"06ed6276","branch":"master"},"scenery":{"sha":"5013941c","branch":"master"},"scenery-phet":{"sha":"2286294f","branch":"master"},"sherpa":{"sha":"97e70540","branch":"master"},"sun":{"sha":"a423abfb","branch":"master"},"tambo":{"sha":"296cf3ba","branch":"master"},"tandem":{"sha":"1b93c58b","branch":"master"}}
</details>

**Comment by DianaTavares** [comment]
I like the idea of moving the dash line or probably clicking in the graph where the user want to see the graph values. I don't think that clicking in the X or Y axis is a good idea because this don't have numeric values.

**Comment by phet-steele** [comment]
> I don't think that clicking in the X or Y axis is a good idea because this don't have numeric values.

@DianaTavares I meant clicking on these values:

![image](https://user-images.githubusercontent.com/5863899/48014125-38351100-e0e3-11e8-9632-8ad7aaaaaa1b.png)

**Comment by DianaTavares** [comment]
Oh I understand! yes you are right! dragging that values or clicking directly in the graph as other options to move the point is a good idea! I like it, lets see what @ariel-phet think

**Comment by KatieWoe** [comment]
In addition, if you are zooming in on the X axis, the point moves to the furthest right value available.  Whatever we decide to do, I think we should be consistent here.

**Comment by DianaTavares** [comment]
I am agree with @KatieWoe. With the actual behavior, if I put the point in from example 8 in the x axe, if I change the zoom to 6, the sim push the dot from 8 to the 6 that is the furthest right value. I think that X should to have the same behavior that Y, move with the graph, no mater if the point go out of the visible graph. 

what do you think @ariel-phet ?

**Comment by DianaTavares** [comment]
The two topics in this issue were discussed in Design meeting and are in issue #62 Closing this one.
