### ISSUE TITLE
Max Y value can be covered by the line

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#58]
For https://github.com/phetsims/QA/issues/215
It is possible for the red line to cover part of the white value on the y axis that gives a sense of scale for that axis of the graph.  To do this set the temperature as high as possible, zoom in on the y-axis as much as possible, and zoom out as much as possible on the x-axis.  The more that is going on (saved lines, intensity, etc.) the more obvious this problem can become.  One potential solution is to move those values over to the left a bit and shrink them so they don't overlap with the zoom buttons.
![coverup](https://user-images.githubusercontent.com/41024075/48159696-2db97980-e293-11e8-9bb2-1eec66c45d36.PNG)
![coveruptwo](https://user-images.githubusercontent.com/41024075/48159697-2e521000-e293-11e8-9a38-1086b8a00243.PNG)

**Comment by DianaTavares** [comment]
It's also other issues with the numbers that I think that the first step is use integer numbers from 700 to 100, one decimal from 99.9 to 10.0, two decimals from 9.99 to 0.01 and then scientific notation using only one digit.

![screen shot 2018-11-07 at 3 29 55 pm](https://user-images.githubusercontent.com/26031501/48165185-03bb8380-e2a2-11e8-8580-0700f7e2db23.png)

The same with the top number for the Y-axe. The labels from 700 to 0.22 are good, but my suggestion si change the others to:
0.05
9X10^-3
2X10^-3
4X10^-4
7X10^-5
1X10^-5

In this moment, the label change size according with the digits of the number to fit in the space. I think that with this changes all the numbers can have the same size and have room to move it a little to the right and not be covered by the graph in the situation that @KatieWoe find, and also move the number a little closer to the edge of the graph  that is a @jbphet suggestion.

![screen shot 2018-11-07 at 3 46 42 pm](https://user-images.githubusercontent.com/26031501/48165935-6b72ce00-e2a4-11e8-8b29-9e94b064be2a.png)

one question is if moving the axe number label mean to move the zoom buttons?

What do you think @ariel-phet ?

**Comment by KatieWoe** [comment]
@DianaTavares @arnabp it looks like the red line almost goes outside of the graph at these types of extremes.  If you zoom out on the x axis all the way the red line looks like its bellow the graph.  Putting here instead of making a new issue as I believe the underlying issue may be similar.  Let me know if you want them separate.
![underline](https://user-images.githubusercontent.com/41024075/48167090-d96cc480-e2a7-11e8-81ab-47b09544d3b8.PNG)

**Comment by DianaTavares** [comment]
I think that in general the graph should not go over the white lines in the axes. 
Now:
![screen shot 2018-11-07 at 4 18 17 pm](https://user-images.githubusercontent.com/26031501/48167401-d6260880-e2a8-11e8-88db-2548d87f7e40.png)

How it should be
![screen shot 2018-11-07 at 4 18 32 pm](https://user-images.githubusercontent.com/26031501/48167405-d7efcc00-e2a8-11e8-911c-78ae9e09c20e.png)

@arnabp, can you make that no mater what close is the graph to the axes, this never go over the white lines?

**Comment by phet-steele** [comment]
@DianaTavares that is confusing. The white line IS the X axis, and with every graph I've seen in my life, y=0 is directly on the X axis. If the red line never touches the X axis, then that would mean the line never reaches y=0. Is that what you want?

The illusion in https://github.com/phetsims/blackbody-spectrum/issues/58#issuecomment-436812125 is simply the tick marks getting so close together that they almost look like a solid line, but this line is not the X axis.

**Comment by DianaTavares** [comment]
This issue was decided how to solved in the design meeting and its include in the To Do list in issue #62. Closing
