### ISSUE TITLE
Should intensity shading go behind the line?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#59]
For https://github.com/phetsims/QA/issues/215
I noticed that, near the edges, the intensity shading makes some odd looking points.  It also gives the appearance of two lines where it covers part of the red line.  This is particularly noticeable when looking at the far left or right, where the red line appears to have wedges or corners.  Layering the intensity shading behind all the lines may solve this.
![pix](https://user-images.githubusercontent.com/41024075/48160366-e502c000-e294-11e8-8821-74b10e384e99.PNG)
![pixtwo](https://user-images.githubusercontent.com/41024075/48160373-e8964700-e294-11e8-9f09-0aadad708e23.PNG)

**Comment by DianaTavares** [comment]
Yes, the intensity shading should go behind the red line.

**Comment by arnabp** [comment]
Intensity shading is now behind axes and graph lines
