### ISSUE TITLE
Active and saved lines should have similar behavior to Graphing Quadratics

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#60]
For https://github.com/phetsims/QA/issues/215
In the sim at the moment, the red line is layered behind any saved lines, meaning that as it moves it can hide behind existing lines.  Compare this to graphing quadratics, which starts with the saved line in front and that saved line moves back when adjustments are made to the red line.

**Comment by DianaTavares** [comment]
I review graphic quadratics and I like that effect where the saver line (the gray one) has the border color of the moving graph (black one)when bout are overlapped. 

![screen shot 2018-11-07 at 3 09 47 pm](https://user-images.githubusercontent.com/26031501/48164280-492a8180-e29f-11e8-8e4f-e4f72b68e7c8.png)

this is the way that may look with Blackbody 

![screen shot 2018-11-07 at 3 17 02 pm](https://user-images.githubusercontent.com/26031501/48164626-43816b80-e2a0-11e8-8952-236de8e01169.png)

And I am agree that the interactive line should be over the saved graphs. 

What do you think @ariel-phet ?

**Comment by ariel-phet** [comment]
@DianaTavares I agree, that is a nice solution in graphing quadratics that we should apply hear as well

**Comment by arnabp** [comment]
The saved line is now smaller than the main line, creating an outline effect when it's saved and increasing visibility of both lines when overlapped, closing.

**Comment by KatieWoe** [comment]
This behavior isn't exactly what was meant.  In Graphing Quadratics the active line is only behind the saved lines until some sort of interaction occurs.  After interaction occurs the active line is layered at the front.  This can be seen in the first screen, which is more comparable in behavior to this sim, but easier to demonstrate on the second screen, as shown bellow.  I believe this is what was meant above.  In https://github.com/phetsims/QA/issues/285 the active line is permanently behind the saved line.  Up to @DianaTavares and @ariel-phet if they want it changed.  If not, feel free to close.
![howgqdoesit](https://user-images.githubusercontent.com/41024075/53376561-f5aa7500-391b-11e9-847e-67255b96ba81.gif)

**Comment by DianaTavares** [comment]
I really like that the active line stay in from of the saved lines. I am agree with @KatieWoe that implemente the same behavior that graphing quadratics is nicer. What do you think @ariel-phet?

**Comment by ariel-phet** [comment]
@DianaTavares I agree, the behavior should match graphing quadratics.

**Comment by arnabp** [comment]
The saved graph now appears in front of the main graph whenever it's created, then moves behind the main graph as soon as the main graph changes in any way. This should match with the graphing quadratics behavior.
