### ISSUE TITLE
Temperature arrow doesn't immediately change color

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#61]
For https://github.com/phetsims/QA/issues/215
Very minor.  As the cursor moves over the temperature control it turns in to a hand to indicated it can be dragged and the arrow changes its shade.  It is possible to have the cursor change to a hand but no color change occur.
![colour](https://user-images.githubusercontent.com/41024075/48166414-b80ad900-e2a5-11e8-80e8-16f9855d37f4.gif)

**Comment by arnabp** [comment]
The entire slider was still part of the sim and could be seen with cursor hover and could be clicked on to change temperature, despite being transparent. I've removed the slider completely.
