### ISSUE TITLE
Pixel polishing round #3

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/blackbody-spectrum#62]
This are the changes that were decided in Design meeting: 

- [x] for the readout in the point value Y coordinate, only use 3 digits value and then change to scientific notation. The same the top number for the Y-axe. The labels from 700 to 0.22 are good, but my suggestion si change the others to:
0.05
9X10^-3
2X10^-3
4X10^-4
7X10^-5
1X10^-5
- [x] Move the Y axe  zoom buttons one side to another one and put it over the label number and put that number where better associate with the label of the Y axe. Something like this:
![screen shot 2018-11-08 at 4 05 07 pm](https://user-images.githubusercontent.com/26031501/48232808-1e5c2e00-e370-11e8-90a4-08018c8aca21.png)

- [x] Put black circles behind the BGR cicles in the projector mode screen 
- [x] Change the number readout for the graph values to yellow in black background
![screen shot 2018-11-08 at 4 05 58 pm](https://user-images.githubusercontent.com/26031501/48232837-37fd7580-e370-11e8-856f-799f13187c56.png)

- [x] Change the "Blackbody Temperature" text found to the same side and style that the labels axes.
- [x] The minor lines are going to desapegar in the X     -axe
- [x] Cut the y graph when go out of range of the graph (don't go over the electromagnetic spectrum label) 
![screen shot 2018-11-08 at 4 08 37 pm](https://user-images.githubusercontent.com/26031501/48232940-94f92b80-e370-11e8-9c6f-1d2d28083688.png)

- [x]  the dot have to move to the right with the peak value of the graph (same behavior that the  Y axes)
- [x] The yellow lines are going to be draggable, but only the vertical line. 
- [x] rainbow don’t match with the visible label little line
![screen shot 2018-11-08 at 4 09 20 pm](https://user-images.githubusercontent.com/26031501/48232965-af330980-e370-11e8-80f0-ddf9340ddbcc.png)

- [x] Don’t make the checkboxes smaller when turn on the intensity
![screen shot 2018-11-08 at 4 09 45 pm](https://user-images.githubusercontent.com/26031501/48232981-beb25280-e370-11e8-8a12-29e336b625ed.png)
![screen shot 2018-11-08 at 4 09 50 pm](https://user-images.githubusercontent.com/26031501/48232986-c5d96080-e370-11e8-867c-9a843beb8c2e.png)

**Comment by arnabp** [comment]
All changes have been added as of [1.0.0-dev.13](https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-dev.13/phet/blackbody-spectrum_en_phet.html). However, the "rainbow don’t match with the visible label little line" issue was fixed by tweaking values to make the rainbow line up instead of addressing the core issue. I'll be continuing to find the source of that issue.

**Comment by arnabp** [comment]
Found and fixed the bug causing the "rainbow don't match with the visible label little line" issue! Closing.
