### ISSUE TITLE
Screen goes blank on iPad

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#65]
**Device**
iPad Air 2
**OS**
iOS 12.1
**Browser**
_Safari_
**Problem Description**
For https://github.com/phetsims/QA/issues/215
Zooming in on the y-axis causes significant lag on the iPad and often leads to either part of the sim, or the whole sim, disappearing.  When this occurs the sim must be restarted entirely.  Occurs in both normal and projector mode.
**Steps to reproduce**
1. Change the temperature slider and note performance
2. Put the temperature at a low setting
3. Zoom the y axis in as far as possible
4. Drag the temperature slider and note performance.  Disappearance should occur as well
5. If temperature is high before zoom in, the sim will disappear when it reaches full zoom.

**Screenshots**
![image from ios](https://user-images.githubusercontent.com/41024075/48741459-6c96ea00-ec18-11e8-90b6-64b57589be70.png)
https://drive.google.com/file/d/1WyfChbdHZdrg-mHYZBnnwMPQt-aNPq1Y/view?usp=sharing

**Comment by KatieWoe** [comment]
Slider may still be manipulated like this, and lowering temperature may bring back visuals.  This has also led to one crash of the sim.

**Comment by KatieWoe** [comment]
Second Update: Seems to be a Safari problem, not an iPad problem.  Occurs on Mac OS 10.14 Safari as well.  No sign on Mac OS 10.14 Chrome or Firefox.

**Comment by phet-steele** [comment]
With that last comment https://github.com/phetsims/blackbody-spectrum/issues/65#issuecomment-440086146, this is probably just #63, no?

**Comment by KatieWoe** [comment]
Looks like actually.  Sorry about that.  Marking as duplicate and closing.
