### ISSUE TITLE
Red line image key shifts back and forth

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#66]
**Device**
iPad Air 2
**OS**
iOS 12
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/QA/issues/215
When the saved line legend appears, the red lines key image can shift right to left.  This occurs when the length of the temperature string changes.
**Steps to Reproduce**
1. Save a line
2. Move the temperature slider up and down, from the top to the bottom

**Screenshots**
https://drive.google.com/file/d/1oBB8lrARYtYewD4N3btSPO0JxfLVVp14/view?usp=sharing

**Comment by DianaTavares** [comment]
Good catch. Definitely should not move

**Comment by phet-steele** [comment]
This is what I was pointing out in #50 and it should be fixed with the solution posed there. Sorry if I was not being clear.

**Comment by KatieWoe** [comment]
Closing as duplicate
