### ISSUE TITLE
Won't load in Internet Explorer

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#67]
For https://github.com/phetsims/QA/issues/215
The sim does not load in internet explorer.  The screen is stuck on the loading screen with a partially filled loading bar.
This is the console with error that occurs.
![iewontload](https://user-images.githubusercontent.com/41024075/48802933-cefdf200-eccd-11e8-8743-301c273b0c93.PNG)

**Comment by KatieWoe** [comment]
This is fixed as of 1.0.0-dev-13.  Noting here that performance on IE is quite laggy on the thermometer.

**Comment by arnabp** [comment]
Since loading issue appears to be fixed, I'm closing. I will note however, that general performance issues will continue to be observed and fixed on a general basis.
