### ISSUE TITLE
Touch controls for moving point only on x axis

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#68]
When moving the value point, it only moves when dragged along the x axis.  This did not present much problem, but did in graphing quadratics, see https://github.com/phetsims/graphing-quadratics/issues/117.  Specific code change was made to that sim, and may be worth examining here.

**Comment by arnabp** [comment]
This was discussed in the last pixel polish meeting, and decided that the point should be draggable only on the x axis, closing.
