### ISSUE TITLE
curve behavior

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/blackbody-spectrum#69]
In Graphing Quadratics https://github.com/phetsims/graphing-quadratics/issues/117, @KatieWoe said:
> This is also recently seen in Blackbody spectrum, though the curve was generally less sharp so the effect is less noticeable.

And:
> @DianaTavares since you're the designer for blackbody-spectrum, what do you think? Do you want an issue for this?

**Comment by KatieWoe** [comment]
Duplicate of https://github.com/phetsims/blackbody-spectrum/issues/68.  Closing with link to issue.
