### ISSUE TITLE
Touch area adjustment to thermometer control 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/blackbody-spectrum#70]
@arnabp currently the touch area of the thermometer pointer can overlap the ResetAllButton when put to its lowest point. The touch area for the pointer is more than generous and can be reduce in the y-dimension. A square aspect ratio to this touch area would be fine.

![bbtoucharea](https://user-images.githubusercontent.com/4051174/51953773-e4dd1100-23fa-11e9-8bb2-4c2b2e6b229f.PNG)

**Comment by arnabp** [comment]
Touch area is no longer dilated across that axis (ends at tips of the cueing arrows instead), closing
