### ISSUE TITLE
Small design pass on y axis labels, scientific notation, and number resizing

### ISSUE THREAD

**Issue by arnabp** [phetsims/blackbody-spectrum#71]
@ariel-phet @DianaTavares I've done a number of changes involving the graph point label and y-axis max label as per #62. I made a lot of discretionary tweaks to when a label resizes, and how much it resizes by, when switching in and out of scientific notation. Can you play around with it a bit and see if it looks right? Do any of the sizes seem off?

[Blackbody Spectrum 1.0.0-dev.13](https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-dev.13/phet/blackbody-spectrum_en_phet.html)

**Comment by DianaTavares** [comment]
Nice Work @arnabp!!  I really like it! 

one of the things is that in scientific notation the labels of the dot is bigger that the y-axis max label, and not with regular numbers.

![screen shot 2019-02-12 at 3 26 28 pm](https://user-images.githubusercontent.com/26031501/52672320-c38c2280-2eda-11e9-9655-035727935daa.png)
![screen shot 2019-02-12 at 3 22 16 pm](https://user-images.githubusercontent.com/26031501/52672332-ca1a9a00-2eda-11e9-9339-bf5db73c49be.png)
 
I remember that one of the agreement about the thermometer was to change the temperature in 50 K, but I don't find that written in any issue. But in the way that is in this moment, that the temperature can be change in small steps, strange thing can be observe, like a dot label a little bigger that the max y-axe label

![screen shot 2019-02-12 at 3 17 42 pm](https://user-images.githubusercontent.com/26031501/52672589-84120600-2edb-11e9-9f44-f3a0022d7933.png)

Or that several temperatures has the same Spectral radiance, for example from 1544K to 1603K . 

![screen shot 2019-02-12 at 3 35 00 pm](https://user-images.githubusercontent.com/26031501/52672755-f7b41300-2edb-11e9-8355-496d8738a0f5.png)
![screen shot 2019-02-12 at 3 35 31 pm](https://user-images.githubusercontent.com/26031501/52672756-fb479a00-2edb-11e9-8a17-2a47b4604658.png)

In the beginning I thought that the scientific notation was bigger in text size that the decimal numbers, but not, they are the same:

![screen shot 2019-02-12 at 3 41 55 pm](https://user-images.githubusercontent.com/26031501/52673321-a2790100-2edd-11e9-93a2-6ccf1360c84e.png)
 
Is possible to move the "X" closer to the numbers? (to have the same separation like the one between the 1 and the 0)

**Comment by ariel-phet** [comment]
@arnabp most things look pretty good to me, but there appears to be some unecessary space when the y-axis label changes to scientific notation between the "power of 10" and the multiplication symbol.

Notice in the screenshot below that the Graph Value scientific notation looks appropriately spaced but the y-axis label is a bit oddly spaced. 

![scientific notation](https://user-images.githubusercontent.com/4051174/58606181-af84ea80-8257-11e9-99f4-c92bf590fa7b.PNG)


Found while looking at https://github.com/phetsims/QA/issues/328

**Comment by arnabp** [comment]
Good catch. I've updated the spacing on the y-axis label to be consistent with the graph point label. Looks like that's the last comment on this design pass so I'll go ahead and close this.
