### ISSUE TITLE
"K" should be translatable

### ISSUE THREAD

**Issue by chrisklus** [phetsims/blackbody-spectrum#74]
From https://github.com/phetsims/blackbody-spectrum/issues/33.

In States of Matter, "K" is translatable, so it should be here as well. All other strings look good.

<img width="822" alt="screen shot 2019-02-15 at 3 46 04 pm" src="https://user-images.githubusercontent.com/5618316/52888440-e3b91d00-3138-11e9-9c88-004d003358a8.png">

**Comment by arnabp** [comment]
Added the appropriate string, used the same label name as was used in States of Matter, closing.

**Comment by chrisklus** [comment]
The usage of `kelvinUnitsString` looks good in BlackbodySpectrumScreenView.js, but 'K' is still hard-coded in SavedGraphInformationPanel.js - could you use it there as well?

<img width="1339" alt="Screen Shot 2019-06-25 at 5 27 42 PM" src="https://user-images.githubusercontent.com/5618316/60135027-d5c27b00-976e-11e9-9ec2-cd80708a91a9.png">

**Comment by arnabp** [comment]
Appropriate changes made, leaving open for QA

**Comment by KatieWoe** [comment]
Now that the saved line Ks are translatable, the box can become too large.  There should be a max width.
![toolong](https://user-images.githubusercontent.com/41024075/60616356-7c6dd380-9d8e-11e9-921a-54e77ff587d0.png)

**Comment by arnabp** [comment]
Added the maxWidth, should be good now, closing.
