### ISSUE TITLE
"Blackbody Temperature" label max-width is too wide

### ISSUE THREAD

**Issue by chrisklus** [phetsims/blackbody-spectrum#75]
From https://github.com/phetsims/blackbody-spectrum/issues/33.

When testing with `stringTest=double` or `stringTest=long`, if the sim is constrained by its left and right bounds, "Blackbody Temperature" is cut off.

![kapture 2019-02-15 at 16 37 20](https://user-images.githubusercontent.com/5618316/52890081-07339600-3140-11e9-903e-678d0ca3cb91.gif)

**Comment by arnabp** [comment]
Reduced maxWidth to align with the INSET margins, closing
