### ISSUE TITLE
"doc" directory is missing

### ISSUE THREAD

**Issue by chrisklus** [phetsims/blackbody-spectrum#77]
From #33.

In the blackbody-spectrum repo, there should be a directory called "doc" that contains model.md and implementation-notes.md. 

See https://github.com/phetsims/graphing-quadratics/blob/master/doc/model.md and https://github.com/phetsims/graphing-quadratics/blob/master/doc/implementation-notes.md for an example.

**Comment by arnabp** [comment]
Added appropriate docs
