### ISSUE TITLE
Slight lag of temperature controls in certain situations.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#79]
**Test device:**
Dell and Jordan
**Operating System:**
Win 10 and Mac 10.14
**Browser:**
firefox, chrome, and safari
**Problem description:**
For https://github.com/phetsims/QA/issues/285
Easier to see in slightly slower devices such as the mac.  When both axis of the graph are zoomed far out and the temperature is near the bottom of the scale, the temperature control is noticeably more laggy.
**Steps to reproduce:**
1. Preferably use a slightly slower platform that isn't consistently laggy (so firefox but not edge)
2. Zoom y-axis to 700 and x-axis to 48
3. Drag temperature to lower end of scale and drag it around.

**Screenshots:**
May be hard to see as screen recording sometimes causes lag itself
![lagatlowtemp](https://user-images.githubusercontent.com/41024075/53355655-b9a8ed00-38e6-11e9-92d3-ed8bb8020ffd.gif)

**Troubleshooting information (do not edit):**

<details>

Name: ‪Blackbody Spectrum‬
URL: https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-dev.13/phet/blackbody-spectrum_en_phet.html
Version: 1.0.0-dev.13 2019-02-12 21:36:32 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
Language: en-US
Window: 1536x760
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
This is much more pronounced, and through the entire thermometer, when saved lines are present.

**Comment by KatieWoe** [comment]
This shows the lag better than the earlier example:
![betteratshowinglag](https://user-images.githubusercontent.com/41024075/53363141-0269a180-38f9-11e9-97c8-65f78b8d46ce.gif)

**Comment by arnabp** [comment]
I believe the problem has been identified. Will keep this open to watch out for in future rounds of testing

**Comment by KatieWoe** [comment]
Looks a fair bit better.  Will continue to keep an out and close if nothing else shows up.

**Comment by JRomero0613** [comment]
Looks better, tested on Safari on Jordan.

**Comment by KatieWoe** [comment]
Seems good
