### ISSUE TITLE
User suggestion: enhancements to graph

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/blackbody-spectrum#8]
I was thinking it would be nice to have the possibility of showing Wien's displacement law and Stefan law as well as having the electromagnetic spectrum (with typical sources of different spectral bands) as a bar under the x axis. X and Y axis units and ticks should be better visualized also.

**Comment by DianaTavares** [comment]
For find easily the peak wavelenght, a checkbox "Peak values" was added
![screen shot 2018-01-30 at 10 27 58 am](https://user-images.githubusercontent.com/26031501/35581301-a2c6327c-05a8-11e8-9bba-47c17da4339e.png)

**Comment by DianaTavares** [comment]
electromagnetic spectrum bar under the axis. X 
![screen shot 2018-01-30 at 11 48 56 am](https://user-images.githubusercontent.com/26031501/35584891-9b4ab242-05b3-11e8-94ca-4cc769e21276.png)

**Comment by DianaTavares** [comment]
This is considered in the actual sim design. Thanks for the teacher suggestions!! closing
