### ISSUE TITLE
Projector mode Intensity hard to read

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#80]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/285
The Intensity value in projector mode is written in black on dark grey, making it hard to see.  If this appears differently when projected, let me know.
**Screenshots:**
![hardtoread](https://user-images.githubusercontent.com/41024075/53356948-dc88d080-38e9-11e9-99d3-cbe7d71a08ae.jpg)

Troubleshooting information (do not edit):

<details>

Name: ‪Blackbody Spectrum‬
URL: https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-dev.13/phet/blackbody-spectrum_en_phet.html
Version: 1.0.0-dev.13 2019-02-12 21:36:32 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
Language: en-US
Window: 1536x731
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by DianaTavares** [comment]
@KatieWoe thanks for the observation! @arnabp please change the text to white  in the intensity value in the projector mode.

**Comment by arnabp** [comment]
The intensity value is now always white
