### ISSUE TITLE
Graph Value always shows up on x-axis, but not on y-axis

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#81]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/285
When the Graph Value point is larger then both axis the label number will show up for the x-axis, but not for the y-axis.
**Steps to reproduce:**
1. Select Graph Values
2. Lower temp to about lightbulb
3. Zoom both axis in as much as possible

**Screenshots:**
![pointbeyond](https://user-images.githubusercontent.com/41024075/53357816-f2979080-38eb-11e9-803e-85ee03de0bd5.jpg)

Troubleshooting information (do not edit):

<details>

Name: ‪Blackbody Spectrum‬
URL: https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-dev.13/phet/blackbody-spectrum_en_phet.html
Version: 1.0.0-dev.13 2019-02-12 21:36:32 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
Language: en-US
Window: 1536x731
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by DianaTavares** [comment]
I like the behavior of the x-axis. In that way user can see always the value of the peak, can move all the range of temperatures in the thermometer, without the necessity of being zooming, if the intention is just to see how this values change. My suggestion is change y-axe to do the same that x-axe.
what fo you think @ariel-phet ?

**Comment by ariel-phet** [comment]
@arnabp I think I agree, seems there is no downside to having this behavior be symmetric between the x and y axes, and seems a bit odd for it to be different. Let's have both behave the same way.

**Comment by arnabp** [comment]
y axis label now stays on the graph even if the graph value point goes off the graph
