### ISSUE TITLE
X-axis lacks final tick

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#82]
For https://github.com/phetsims/QA/issues/285. General design question
As seen in the image bellow, the y-axis has an end tick (though no in between ticks).  The x-axis has several in between ticks but does not have one indicating the largest value (in this case .75).  Per @DianaTavares this is a design issue to address.
![endbit](https://user-images.githubusercontent.com/41024075/53425062-9727da00-39a1-11e9-96e1-07da15601839.jpg)

**Comment by DianaTavares** [comment]
@arnabp please add a little line (same size and width that y-axe) to the end of the x-axe.

**Comment by arnabp** [comment]
Added identical tick 👍
