### ISSUE TITLE
Make X in scientific notation a multiplication symbol

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/blackbody-spectrum#89]
For https://github.com/phetsims/QA/issues/320.

Here's what it looks like now:

![Screen Shot 2019-05-21 at 4 50 09 PM](https://user-images.githubusercontent.com/31285590/58135716-be7cf480-7be8-11e9-94d2-77f3e4737673.png)

It should be a multiplication symbol. See https://github.com/phetsims/inverse-square-law-common/issues/50.

Linking to https://github.com/phetsims/blackbody-spectrum/issues/71 since @DianaTavares is requesting changes to scientific notation in that issue.

**Comment by arnabp** [comment]
Changed all three instances of scientific notation to use multiplication symbol
