### ISSUE TITLE
Zooming axis relayers active line

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#90]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/320.  Related to https://github.com/phetsims/blackbody-spectrum/issues/60
When the graph axes are zoomed in or out, the red active line is moved behind the grey solid line, even when it was moved and brought to the front before.
**Steps to reproduce:**
1. Save at least one line
2. Move the thermometer to bring the red line to the front.  Make sure lines still overlap some
3. Zoom in the x-axis (or y-axis)
4. Observe the two lines
5. Move the thermometer again and observe

**Screenshots:**
![zoomrelayers](https://user-images.githubusercontent.com/41024075/58187961-13664c80-7c75-11e9-96b3-d6c14afd9146.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Blackbody Spectrum‬
URL: https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-dev.16/phet/blackbody-spectrum_en_phet.html
Version: 1.0.0-dev.16 2019-05-21 21:44:52 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by DianaTavares** [comment]
good catch @KatieWoe. Yes, it look strange, it need to be fixed.

**Comment by arnabp** [comment]
Changes to layering of active and saved lines should now match up with expected behavior, closing
