### ISSUE TITLE
Graph Value line disappears

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#93]
**Device**
Hopper
**OS** 
iOS 12.3
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/QA/issues/320
When the graph values point/line is dragged to the edge of the x-axis, the x line turns invisible.  It can be dragged to that point without any zooming, but once let go of, it can't be picked up.  If the point is bellow the y-axis max, it can be seen and dragged.
On Slack: 
```
Arnab Purkayastha [1:46 PM]
So you're saying that because the x value gets stuck at the 1.5 when dragging the point that the dashed line should still be visible at the edge? I think that's a better way of doing it.

Originally the line could be dragged past 1.5 but would just turn invisible. But then the behavior was changed so it would stop at 1.5, but it was never changed so the dashed line remained visible.
```
**Steps to Reproduce:**
1. Zoom in y, and possibly x axis so that the line you are using has a max point in the x bounds, but the entire right side is above the y bounds
2. Turn on graph values
3. Grab the dotted line for the point and drag to the far right.
4. Let go

**Screenshots**
![yellowgone](https://user-images.githubusercontent.com/41024075/58204237-225ef600-7c99-11e9-9d6b-7e4cb481d681.gif)

**Comment by arnabp** [comment]
Fixing this made me remember that the reason it was like this to begin with was that we DO want the line to disappear when the point node goes off the graph when adjusting temperature. But we don't want it to go off stage when it's being dragged. It's been adjusted accordingly now.
