### ISSUE TITLE
the rainbow looks strange (several parallel lines in the picture) 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/blackbody-spectrum#95]
Test device: MacBook Air (13-inch, 2017)

Operating System: macOS Mojave

Browser: Chrome Version 74.0.3729.169 (Official Build) (64-bit)

Problem description: when I zoom in in the rainbow, it have several parallel vertical lines.

Steps to reproduce:
zoom in the x-axes to see the rainbow 

Screenshots:

![Screen Shot 2019-05-23 at 9 34 28 AM](https://user-images.githubusercontent.com/26031501/58267927-b71d2e80-7d41-11e9-8633-fe18bbff3960.png)

Troubleshooting information (do not edit):
Name: ‪Blackbody Spectrum‬
URL: http://phettest.colorado.edu/blackbody-spectrum/blackbody-spectrum_en.html?ea&brand=phet
Version: 1.0.0-dev.16 (require.js)
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Language: es-419
Window: 1440x721
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by arnabp** [comment]
@KatieWoe Would you be able to see about recreating this on any of the test machines? I wasn't able to recreate this on my machine and I talked to @DianaTavares who said it's possible it's something strange going on in her system specifically.

**Comment by KatieWoe** [comment]
I'll take another look.

**Comment by KatieWoe** [comment]
From Slack:
```
Arnab Purkayastha [12:15 PM]
Hey, before you get too far into testing that blackbody spectrum issue, just found out that Diana was apparently looking at prettest instead of the dev version when she found the bug, and now I can recreate it. So you don’t need to look into it, sorry about that.
```

**Comment by arnabp** [comment]
Making a note here that this issue is a result of https://github.com/phetsims/scenery-phet/issues/500

**Comment by arnabp** [comment]
This has been resolved as a result of the changes to scenery, closing.
