### ISSUE TITLE
Reposition zoom controls for x-axis

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/blackbody-spectrum#96]
The zoom controls for the x-axis are a bit tight to the number on the axis, there should be a bit more negative space. I think the same amount of negative space that is between the zoom controls and the number on the y-axis should be between the number on the x-axis and its zoom controls.

Found as part of https://github.com/phetsims/QA/issues/328

Here is an adjusted screenshot

![bb](https://user-images.githubusercontent.com/4051174/58605640-b6126280-8255-11e9-96a1-c29198815fdc.PNG)

**Comment by arnabp** [comment]
So technically the zoom buttons were the same distance away from the axes on the x and y sides. But the axis labels on the x-axis side were larger, so the zoom buttons were closer to the text itself. I've adjusted the text to be the same size across both axes. 

Please verify in (blackbody-spectrum/1.0.0-rc.2)[https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-rc.2/phet/blackbody-spectrum_all_phet.html] that it looks okay.

**Comment by ariel-phet** [comment]
Looks good. Closing
