### ISSUE TITLE
Part of Ipad screen gets cut off on ?stringTest=X

### ISSUE THREAD

**Issue by etwa4650** [phetsims/blackbody-spectrum#97]
<b>Test Device</b>

Pauling

  <b>Operating System</b>

IOS 11.4.1

  <b>Browser</b>

 Safari

  <b>Problem Description</b>

For https://github.com/phetsims/QA/issues/328. Right side of screen and slider for thermometer gets cutoff on ?stringTest=X

I don't think this will ever be a problem but figured i would make an issue just in case.

  <b>Steps to Reproduce</b>

?stringTest=X 

  <b>Visuals</b>

![50A4DF1F-0BE6-4384-A791-929BC3BD3A57](https://user-images.githubusercontent.com/26493147/58725669-f4666980-839c-11e9-812c-d90ae71ed3ed.png)

**Comment by arnabp** [comment]
This is a good catch, the layout wasn't implemented very well. I believe I've fixed it up so it shouldn't get cut off on any string tests. Leaving open for future testing.

**Comment by KatieWoe** [comment]
This looks solved 1.0.0-rc.2
