### ISSUE TITLE
Long strings for temp too large

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#98]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/328.  May be connected to https://github.com/phetsims/blackbody-spectrum/issues/97
When string test is long the temperature string goes out of bounds severely.
**Steps to reproduce:**
1. Set up ?dev and stringTest=long
2. Observe

**Screenshots:**
![longextends](https://user-images.githubusercontent.com/41024075/59307209-43dd4d00-8c5b-11e9-891e-514c04598578.png)

Troubleshooting information (do not edit):

<details>

Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-rc.1/phet/blackbody-spectrum_all_phet.html?stringTest=long&dev
Version: 1.0.0-rc.1 2019-05-29 22:54:36 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Shows up with rtl as well

**Comment by arnabp** [comment]
Fixed, should be the last item that wasn't changed for i18n. Will leave open for testing.

**Comment by KatieWoe** [comment]
This looks good on 1.0.0-rc.2
