### ISSUE TITLE
Colors of the star should match the Flash version

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#99]
For https://github.com/phetsims/QA/issues/328.  @DianaTavares and I noticed that the html colors are darker than the flash colors.  It caught my attention in the area that is around the light bulb temperature.  It looks particularly brown to me, which seemed odd.  Creating this issue for discussion of what the colors should look like.

**Comment by DianaTavares** [comment]
The colors in the flash and in the HTML5 version are different (I think that the HTML5 version have a dark background behind the star). For example this pictures with the same temperature in both sims: 
Flash
![Screen Shot 2019-06-11 at 3 48 56 PM](https://user-images.githubusercontent.com/26031501/59309605-417df180-8c61-11e9-99c6-ecc428a6607a.png)

HTML5
![Screen Shot 2019-06-11 at 2 41 02 PM](https://user-images.githubusercontent.com/26031501/59309642-5ce8fc80-8c61-11e9-8872-ceda6dc3dfd6.png)

Both color together:
![Screen Shot 2019-06-11 at 3 51 10 PM](https://user-images.githubusercontent.com/26031501/59309658-66726480-8c61-11e9-9dea-205b35806a0b.png)

looking for references in internet about the color of stars according with the temperature, most of them are very similar to this:

![Screen Shot 2019-06-11 at 3 08 18 PM](https://user-images.githubusercontent.com/26031501/59309726-8d309b00-8c61-11e9-98b5-0c9634f092c7.png)

with orange and red for the lower temperatures. In the Flash we can get orange and red, but in the HTML5, they look like brown. 

Mi suggestion is to use the same colors that the Flash version that is more similar to the references in other websites.

**Comment by ariel-phet** [comment]
@arnabp yes this should be fixed, feel free to use the flash sim as a reference. My guess is that as @DianaTavares pointed out there is something going on with an interaction between the star, its color opacity, and the background. You might need to layer in something on the background of the star, or perhaps they colors just need to be at full opacity.

**Comment by arnabp** [comment]
Yep, I've changed the opacity of the star to be more forgiving at the mid-range of the thermometer. All the colors are closer to what they should be now, and opacity decreases occur more aggressively under light bulb temperature now.
